devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 


#導航到project 的url
urlpatterns = [
    path('admin/', admin.site.urls ),
    path('projects/',include('projects.urls')), #開頭為空白的會被丟到projects.url 處理
    path('',include('users.urls')), # #開頭為users的會被丟到users.url 處理
   
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from nturl2path import url2pathname
from django.urls import path
from . import views

urlpatterns = [
    path('login/',views.loginUser, name="login"),
    path('logout/',views.logoutUser, name="logout"),
    path('register/',views.registerUser, name="register"),


    path('',views.profiles, name="profiles"),
    path('profile/<str:pk>/',views.userProfile, name="user-profile"),

]

projects/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
import uuid
from users.models import Profile

# Create your models here.
# 在這裡 Project 和 Review 是一對多關係  Project 和Tag是多對多關係



class Project(models.Model):
    owner = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
    title = models.CharField(max_length = 200)
    description = models.TextField(null=True,blank=True) #can be empty
    featured_image = models.ImageField(null=True,blank=True,default="default.jpg")
    demo_link = models.CharField(max_length = 2000, null=True, blank=True)
    source_link = models.CharField(max_length = 2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True) #與下面的Tag 是 Many to Many 關係 #重要
    vote_total = models.IntegerField(default=0,null=True, blank=True)
    vote_ratio = models.IntegerField(default=0,null=True, blank=True)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True, editable=False)

    
    def __str__(self):
        return self.title



class Review(models.Model):
    VOTE_TYPE = (
        ('up','UP Vote'),
        ('down','Down Vote'),
    )
    #owner
    project = models.ForeignKey(Project, on_delete=models.CASCADE) #重要
    body = models.TextField(null=True,blank=True)
    value =  models.CharField(max_length = 200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True, editable=False)

    def __str__(self):
        return self.value

# create a many to many relation between upper two

class Tag(models.Model):
    name = models.CharField(max_length = 200)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True, editable=False)

    def __str__(self):
        return self.name




    




 

users/models.py
from django.db import models
from django.contrib.auth.models import User 
import uuid
# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE,null=True,blank=True) #每個user 跟 profile 同時生成 1對1關係
    name = models.CharField(max_length=200,blank=True,null=True)
    email = models.EmailField(max_length=500,blank=True,null=True)
    username = models.CharField(max_length=200,blank=True,null=True)
    location = models.CharField(max_length=200,blank=True,null=True)
    short_intro = models.CharField(max_length=200,blank=True,null=True)
    bio = models.TextField(blank=True,null=True)
    profile_image = models.ImageField(null=True,blank=True,upload_to='profiles/',default='profiles/user-default.png')
    social_github = models.CharField(max_length=200,blank=True,null=True)
    social_twitter = models.CharField(max_length=200,blank=True,null=True)
    social_linkedin = models.CharField(max_length=200,blank=True,null=True)
    social_youtube = models.CharField(max_length=200,blank=True,null=True)
    social_website = models.CharField(max_length=200,blank=True,null=True)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200,blank=True,null=True)
    description = models.TextField(blank=True,null=True)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True, editable=False)


    def __str__(self):
        return str(self.name)




    

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','email','username','password1','password2']
        labels = {
            'firse_name' : "Name" #改名字
        }

users/views.py
from pydoc import describe
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.http import HttpResponse
from .models import Profile
from django.contrib.auth.models import User 
from .forms import CustomUserCreationForm


# Create your views here.

# 1. 瀏覽器送出 HTTP request
# 2. Django 依據 URL configuration 分配至對應的 View
# 3. View 進行資料庫操作並回傳 HttpResponse 物件
# 4. 瀏覽器依據 HTTP response 顯示網頁

# 舉例Login的例子來說
# 透過url view render進入login_register.html
# 此時沒有POST method
# def loginPage 還沒被啟動
# 再來 當按下submit 的時候 POST Method 的request被送出 （
# !!! 重點submit 出來的訊息 放在action裡面的url 處理 若action 為空字串 送到前一個介面
# def loginPage 啟動
# https://ithelp.ithome.com.tw/articles/10204953


def loginUser(request):
    page = 'login'
    context = {'page':page }

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request,"Username does not exist")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request,user) #create a user session in User's table and add it to browser's cookie 
            return redirect('profiles')
        else:
            messages.error(request,'Username OR password is incorrect')

    return render(request,'users/login_register.html')

def logoutUser(request):
    logout(request) #delete the session
    messages.error(request,"User was log out")
    return redirect('login')

def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request,"User account was created")

            login(request,user)
            return redirect('profiles')
        
        else:
            messages.success(request,"An error has occurred during registration")


    context = {'page':page, 'form':form }
    return render(request, 'users/login_register.html',context)


def profiles(request):
    profiles=Profile.objects.all()
    context = {'profiles':profiles}
    return render(request,'users/profiles.html',context)


def userProfile(request,pk):
    profile = Profile.objects.get(id=pk)
    topSkills = profile.skill_set.exclude(description__exact="")

    otherSkills = profile.skill_set.filter(description="")

    context = {'profile':profile,'topSkills':topSkills,'otherSkills':otherSkills}
    return render(request,'users/user-profile.html',context)

users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

{% if page == 'register' %}

<h1> Register User</h1>

<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Register</h3>
        <p>Create a new developer account</p>
      </div>

      <form action="{% url 'register' %}" method="POST" class="form auth__form">
        {% csrf_token %}
        {% for field in form %}
        <div class="form__field">
            <label for="formInput#text">{{field.label}} </label>
            {{field}}
          </div>

        {% endfor %}
        <!-- Input:Text -->
        <div class="form__field">
          <label for="formInput#text">Full Name: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="text"
            placeholder="e.g. Dennis Ivanov"
          />
        </div>


        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
        </div>

      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="{% url 'login' %}">Log In</a>
      </div>
    </div>
  </div>

{% else %}


<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
      </div>

      <form class="form auth__form" action="{% url 'login' %}" method="POST">
        <!-- Input:Username -->

        {% csrf_token %}
        <div class="form__field">
            
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>

        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="forgetpassword.html">Forget Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url 'register' %}">Sign Up</a>
      </div>
    </div>
  </div>
{% endif %}

{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}
    <h1>User Profiles</h1><main class="home">
        <section class="hero-section text-center">
          <div class="container container--narrow">
            <div class="hero-section__box">
              <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
              <h2>FROM AROUND THE WORLD</h2>
            </div>
    
            <div class="hero-section__search">
              <form class="form" action="#" method="get">
                <div class="form__field">
                  <label for="formInput#search">Search Developers </label>
                  <input class="input input--text" id="formInput#search" type="text" name="text"
                    placeholder="Search by developer name" />
                </div>
    
                <input class="btn btn--sub btn--lg" type="submit" value="Search" />
              </form>
            </div>
          </div>
        </section>
        <!-- Search Result: DevList -->
        <section class="devlist">
          <div class="container">
            <div class="grid grid--three">

            {% for profile in profiles %}
              <div class="column card">
                <div class="dev">
                  <a href="{% url 'user-profile' profile.id %}" class="card__body"> 
                    <!-- 這裡 profile.id 巧妙的創造一個link -->
                    <div class="dev__profile">
                      <img class="avatar avatar--md" src="{{profile.profile_image.url}}" alt="image" />
                      <div class="dev__meta">
                        <h3>{{profile.name}}</h3>
                        <h5>{{profile.short_intro|slice:"10"}}</h5>
                      </div>
                    </div>
                    <p class="dev__info">{{profile.bio|slice:"150"}}
                    </p>
                    <div class="dev__skills">

                    {% for skill in profile.skill_set.all|slice:"5" %}
                      <span class="tag tag--pill tag--main">
                        <small>{{skill}}</small>
                      </span>
                    {% endfor %}

                    </div>
                  </a>
                </div>
              </div>
            {% endfor %}

            </div>
          </div>
        </section>

      </main>
{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">

                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}

                {% if profile.social_youtube %}
                <li>
                  <a title="Stackoverflow" href="{{profile.social_youtube}}" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                {% endif %}

                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}

                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
                {{profile.bio}}
            </p></div>

            <div class="devInfo">
                <h3 class="devInfo__title">Skills</h3>
                {% for skill in topSkills %}
                <div class="devSkill">
                    <div class="devSkill">
                        <h4 class="devSkill_title">{{skill.name}}</h4>
                        <p class="'devSkill_info"> {{skill.description}}</p>

                    </div>
                {% endfor %}
                




              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">

                {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill}}</small>
                </span>
                {% endfor %}

              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

            {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="profile.html">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}